### ISSUE TITLE
(ssis-vs2022) This package does not support 32 bit architecture

### ISSUE THREAD

**Issue by jezuk** [bbtsoftware/chocolatey-packages#131]
Hello,

When trying to install the ssis-vs2022 package on my Windows 11 (64-bit) system I get the error:

```
Chocolatey v2.3.0 Business
Installing the following packages:
ssis-vs2022
By installing, you accept licenses for the packages.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading ssis-vs2022 1.4.0... 100%

ssis-vs2022 v1.4.0 [Approved]
ssis-vs2022 package files install completed. Performing other installation steps.
ERROR: This package does not support 32 bit architecture.
The install of ssis-vs2022 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\ssis-vs2022\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - ssis-vs2022 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ssis-vs2022\tools\ChocolateyInstall.ps1'.
 See log for details.
```

I can see this was addressed in https://github.com/bbtsoftware/chocolatey-packages/pull/130/files

However it appears this change hasn't been uploaded to the community repo yet.

Thanks

**Comment by christianbumann** [comment]
hi @jezuk 

As you have already seen, we have already fixed the problem. Unfortunately the choco package has already been published. We hoped that no one would notice until the next release from Microsoft.
Now it happened, and thank you for reporting it.

If you urgently need a fix, we will ensure that the chocolatey package is deleted by the community and re-imported.

Otherwise we would prefer to take the easy route and wait for Microsoft to fix it.

Best regards

Christian

**Comment by jezuk** [comment]
hi @christianbumann

If you are able to upload a fixed version that would be great, I'm not sure how long we will need to wait until a new Microsoft release.

I think you can upload a new version without requiring the existing one to be deleted https://docs.chocolatey.org/en-us/create/create-packages/#package-fix-version-notation

Thanks for creating the package!

Jez

**Comment by christianbumann** [comment]
@jezuk I just created a fixed package and pushed it. it's in moderation
https://community.chocolatey.org/packages/ssis-vs2022/1.4.0.20240814
