### ISSUE TITLE
AppVeyor install silent disappears

### ISSUE THREAD

**Issue by jayvdb** [bbtsoftware/chocolatey-packages#77]
The bower package is the only one I have tested with, but I assume the problem exists with the others...

I ran into this problem on AppVeyor, using its pre-installed nodejs, where `cinst bower` is installing into `C:\Users\appveyor\AppData\Roaming\npm\` for builds of branches, with `C:\Users\appveyor\AppData\Roaming\npm` in the registry `HKEY_CURRENT_USER\Environment` key `PATH`.  You can see a branch build with a bit of debugging at https://ci.appveyor.com/project/coala/package-manager/builds/25148463

But when I create a pull request, `bower` installs correctly however it has disappeared.
My guess is that AppVeyor is attempting some sort of security, likely due to their paying customers.  I'm doing a test run now to find out what is in the registry, etc, for these pull requests.  It will appear at https://ci.appveyor.com/project/coala/package-manager/builds/25148080 (it is blocked atm)

It is expected that choco installs are system wide, not user specific.

I see the `chocolateyInstall.ps1` is doing `npm install -g bower` , so this isnt a 'bug' in the choco package, but the installer also isnt emitting an error or warning, and I am pretty sure we can fix that.

More analysis to come ...

**Comment by jayvdb** [comment]
Gosh, it is working now that I have added some debugging.

The failure can be seen at https://ci.appveyor.com/project/coala/package-manager/builds/25147543/job/tohwu65icm3uwvqm#L1126

Other than gamma rays, the other change is that I did a branch build which was green and populated the AppVeyor caches, but I dont have `C:\Users\appveyor\AppData\Roaming\npm\` listed as a cache directory so that shouldnt be effecting it.  Ho hum.

**Comment by pascalberger** [comment]
@jayvdb I wasn't able to reproduce it. Having [this](https://github.com/pascalberger/AppVeyor-Bower/blob/master/.appveyor.yml) AppVeyor configuration, build for a pull request was able to install and call bower: https://ci.appveyor.com/project/pasacalberger/appveyor-bower/builds/25153803

**Comment by jayvdb** [comment]
Thanks for trying.
I tried a simpler cut down version of my build environment at https://github.com/pascalberger/AppVeyor-Bower/pull/2 , but it works lovely.
Closing for now, as I am also not seeing it in my coala builds.  I'll be back if it re-occurs, hopefully with more info ;-)
