### ISSUE TITLE
(vscode-cake) Add dependency to vscode-csharp

### ISSUE THREAD

**Issue by pascalberger** [bbtsoftware/chocolatey-packages#81]
Cake extension requires the C# extension and therefore should have a dependency on the `vscode-csharp` extension

**Comment by maczamora** [comment]
I wouldn't mind diving into some PowerShell work. May need to take a little refresher on it this weekend, but could see what I can get done.

**Comment by pascalberger** [comment]
@maczamora This change actually doesn't require changes to the PowerShell script, but instead can be done in the [vscode-cake.nuspec](https://github.com/bbtsoftware/chocolatey-packages/blob/master/manual/vscode-cake/vscode-cake.nuspec#L31) file, where dependencies are defined. It requires a dependency to the [vscode-csharp](https://chocolatey.org/packages/vscode-csharp) extension in at least version `1.0.0` (see [Version ranges and wildcards](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards) for syntax)

**Comment by maczamora** [comment]
I submitted a pull request on this. Not sure if it's what you're looking for. Just followed the examples.

**Comment by RedGrinGrumbler** [comment]
is this still open?

**Comment by pascalberger** [comment]
@RedGrinGrumbler There's already an open pull request, which I'll look at soon
